version: "3"
services:
       coingecko_integration:
          container_name: coingecko_integration
          tty: true
          image: node:latest
          restart: always
          build: .
          ports:
            - 6000:6000
          links:
            - coingecko_integration_redis
          working_dir: '/usr/src/app'
          command: ['npm', 'start']
          volumes:
            - .:/usr/src/app
       coingecko_integration_redis:
             container_name: coingecko_integration_redis
             image: redis
             volumes:
               - ./data:/data/db
             ports:
               - '6379:6379'